on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    name: Build bin
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install libgdal-dev
        run: sudo apt update && sudo apt install libgdal-dev -y
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test
      - name: Build Assets
        run: tar -C target/release/ -czvf countme.tar.gz
      - name: Upload Release Assets
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v1
        with:
          files: '*.tar.gz'
