on:
  push:
    tags:
      - "v*.*.*"
jobs:
  github:
    name: Build ubuntu-latest
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - name: Install libgdal-dev
        run: sudo apt update && sudo apt install libgdal-dev -y
      - name: Add target
        run: rustup target add x86_64-unknown-linux-gnu
      - name: Build Assets
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
          tar -C target/x86_64-unknown-linux-gnu/release/ -czvf countme-x86_64-unknown-linux-gnu.tar.gz
      - name: Upload Release Assets
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v1
        with:
          files: '*.tar.gz'
      - name: Upload Artifacts
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v3
        with:
          path: '*.tar.gz'
